version: '2'

networks:
  my-network:
    driver: bridge
services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
    networks:
      - my-network
    volumes:
      - 'openldap_data:/bitnami/openldap'
  postgres:
    image: postgres
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  openidc:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    networks:
      - my-network
    ports:
      - 8080:8080
    depends_on:
      - postgres
  kibana:
    image: kibana:7.14.2
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
    networks:
      - my-network
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:7.14.2
    environment:
      discovery.type: 'single-node'
      bootstrap.memory_lock: 'true'
      xpack.security.enabled: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - my-network
    ports:
      - 9200:9200      
  httpd:
    image: solsson/httpd-openidc:2.4
    networks:
      - my-network
    ports:
      - 18080:80
      - 8056:8056

volumes:
  openldap_data:
    driver: local
  postgres_data:
      driver: local